export const CREATE_GAME_CLEANUP = 'CREATE_GAME_CLEANUP';
export const CREATE_GAME_SET_TITLE = 'CREATE_GAME_SET_TITLE';
export const CREATE_GAME_SET_INVITES = 'CREATE_GAME_SET_INVITES';

export const IN_GAME_CLEANUP = 'IN_GAME_CLEANUP';
export const IN_GAME_SET_LETTER = 'IN_GAME_SET_LETTER';
export const IN_GAME_SET_LOADING = 'IN_GAME_SET_LOADING';
export const IN_GAME_SET_LETTERS_ARRAY = 'IN_GAME_SET_LETTERS_ARRAY';
export const IN_GAME_SET_SCOREBOARD = 'IN_GAME_SET_SCOREBOARD';