export const GAME_SET_TITLE = 'GAME_SET_TITLE';
export const GAME_SET_INVITES = 'GAME_SET_INVITES';
export const CREATE_GAME_START = 'CREATE_GAME_START';
export const CREATE_GAME_SUCCESS = 'CREATE_GAME_SUCCESS';
export const CREATE_GAME_FAIL = 'CREATE_GAME_FAIL';