export const GAME_SET_TITLE = 'GAME_SET_TITLE';
export const GAME_SET_INVITES = 'GAME_SET_INVITES';

export const GAME_SET_LETTER = 'GAME_SET_LETTER';
export const GAME_SET_LOADING = 'GAME_SET_LOADING';
export const GAME_SET_LETTERS_ARRAY = 'GAME_SET_LETTERS_ARRAY';
export const GAME_SET_CLEANUP = 'GAME_SET_CLEANUP';